Repository python-cachier/cachier, pull requests merged in 2024-02, with the labels that each got.

#141 separate dev requirements from package extra
  .github/workflows/checkdocs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.rst
  setup.py
  tests/requirements.txt
Labels: testing and development

#139 add pre-commit and apply
  .flake8
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  tests/requirements.txt
  tests/test_quality.py
  tests/test_security.py
Labels: enhancement, testing and development

#144 Enable separation of MongoDB tests from other tests
  tests/test_defaults.py
  tests/test_general.py
  tests/test_mongo_core.py
Labels: testing and development

#147 use `pytest.param` instead of copy whole test (#145)
  pytest.ini
  tests/test_general.py
  tests/test_mongo_core.py
Labels: enhancement, testing and development

#140 convert `args` to `kwargs` to reduce nb of unique keys
  .ignore
  cachier/core.py
  tests/test_general.py
Labels: enhancement

#148 ci: split tests for local / db [vol.2] (#143)
  .github/workflows/test.yml
Labels: enhancement, testing and development

#151 Proper names for Github Actions jobs
  .github/workflows/checkdocs.yml
  .github/workflows/test.yml
Labels: testing and development

#150 convert `args` to `kwargs` to reduce nb of unique keys (#140)
  .ignore
  cachier/core.py
  tests/test_general.py
Labels: enhancement

#153 precommit: add typos check & fixing some
  .pre-commit-config.yaml
  README.rst
  cachier/_version.py
  cachier/base_core.py
  cachier/pickle_core.py
  tests/test_pickle_core.py
Labels: testing and development

#159 ci: reduce nb running jobs
  .github/workflows/checkdocs.yml
  .github/workflows/test.yml
Labels: enhancement

#164 refactor: replace void try/except with supress
  cachier/_version.py
  cachier/mongo_core.py
  pyproject.toml
  tests/test_general.py
  tests/test_pickle_core.py
  versioneer.py
Labels: enhancement

#165 refactor: move private cores to subpackage
  cachier/core.py
  cachier/cores/__init__.py
  cachier/cores/base.py
  cachier/cores/memory.py
  cachier/cores/mongo.py
  cachier/cores/pickle.py
  setup.py
  tests/test_mongo_core.py
Labels: enhancement

#166 refactor: rename CLI module
  cachier/__main__.py
  cachier/scripts/__init__.py
  setup.py
Labels: enhancement

#163 precommit: introduce Black & docs
  .pre-commit-config.yaml
  cachier/__init__.py
  cachier/__main__.py
  cachier/_version.py
  cachier/core.py
  cachier/cores/base.py
  cachier/cores/memory.py
  cachier/cores/mongo.py
  cachier/cores/pickle.py
  pyproject.toml
  setup.py
  tests/speed_eval.py
  tests/standalone_script.py
  tests/test_core_lookup.py
  tests/test_defaults.py
  tests/test_general.py
  tests/test_memory_core.py
  tests/test_mongo_core.py
  tests/test_pickle_core.py
  tests/test_quality.py
  tests/test_security.py
  versioneer.py
Labels: enhancement, documentation

#171 Contributor update
  README.rst
Labels: documentation

#172 fix: handling default kw arguments
  cachier/core.py
  tests/test_general.py
Labels: bug

#168 resolve using partial in runtime
  cachier/core.py
  cachier/cores/base.py
  tests/test_general.py
Labels: enhancement, complex issue

#178 precommit: introduce prettier
  .pre-commit-config.yaml
Labels: enhancement

#173 update printing with f-strings
  cachier/core.py
  cachier/cores/base.py
  cachier/cores/mongo.py
  cachier/cores/pickle.py
  tests/speed_eval.py
  tests/test_memory_core.py
  tests/test_mongo_core.py
  tests/test_pickle_core.py
Labels: enhancement

#179 ci: set concurrency
  .github/workflows/checkdocs.yml
  .github/workflows/test.yml
Labels: enhancement

#180 automate & simplify release
  .codecov.yml
  .github/workflows/release.yml
  .ignore
  .pre-commit-config.yaml
  MANIFEST.in
  cachier/__init__.py
  cachier/_version.py
  cachier/version.info
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
Labels: enhancement, complex issue, testing and development

#175 refactor: cleaning some more try/except
  cachier/core.py
  cachier/cores/pickle.py
  tests/test_core_lookup.py
Labels: enhancement

#174 precommit: configure pyupgrade
  .pre-commit-config.yaml
  cachier/_version.py
  cachier/core.py
  cachier/cores/mongo.py
  tests/test_general.py
Labels: enhancement

#177 ci: replace dead safety test with GH actions
  .github/workflows/safety.yml
  MANIFEST.in
  requirements.txt
  setup.py
  tests/test_security.py
Labels: enhancement

#185 fix import after install
  .github/workflows/release.yml
  MANIFEST.in
  cachier/_version.py
  setup.py
Labels: bug

#182 minor refactor if depths
  cachier/core.py
Labels: enhancement

#187 upgrade checkout action to v4 in all workflows
  .github/workflows/checkdocs.yml
  .github/workflows/safety.yml
  .github/workflows/test.yml
Labels: testing and development, CI

#191 adjust line length for prettier
  .pre-commit-config.yaml
Labels: testing and development, CI

#186 precommit: use `yesqa` to prune noqa
  .pre-commit-config.yaml
  cachier/_version.py
  cachier/core.py
  cachier/cores/pickle.py
  tests/test_mongo_core.py
  tests/test_pickle_core.py
Labels: enhancement, testing and development, CI

#183 update default args+kwargs hashing
  cachier/core.py
  tests/test_general.py
Labels: enhancement

#192 resolve precommit failing
  .pre-commit-config.yaml
  cachier/_version.py
  pyproject.toml
Labels: bug, CI

#194 ruff: enable `isort`
  cachier/__init__.py
  cachier/_version.py
  cachier/cores/mongo.py
  cachier/cores/pickle.py
  pyproject.toml
  setup.py
  tests/standalone_script.py
  tests/test_memory_core.py
  tests/test_mongo_core.py
Labels: enhancement

#193 refactor: cleaning of using package/global defaults
  .pre-commit-config.yaml
  cachier/__init__.py
  cachier/_types.py
  cachier/config.py
  cachier/core.py
  cachier/cores/base.py
  cachier/cores/memory.py
  cachier/cores/mongo.py
  cachier/cores/pickle.py
  tests/test_core_lookup.py
  tests/test_mongo_core.py
Labels: enhancement, complex issue

#197 tests: add asserts for expected results
  tests/test_general.py
Labels: enhancement

#199 refactor: simplify using property line methods
  cachier/cores/base.py
  cachier/cores/mongo.py
  cachier/cores/pickle.py
Labels: enhancement

#200 clarify that the wrapper function as private
  cachier/core.py
Labels: enhancement

#196 fixing wrong results for runtime func
  cachier/cores/memory.py
  cachier/cores/pickle.py
  tests/test_general.py
Labels: bug

#195 ci: switch from hosted to local DB
  .github/workflows/test.yml
  README.rst
  tests/test_mongo_core.py
Labels: enhancement

#198 refactor: clarify the casher arguments
  README.rst
  cachier/config.py
  cachier/core.py
  tests/test_defaults.py
  tests/test_general.py
  tests/test_memory_core.py
  tests/test_mongo_core.py
  tests/test_pickle_core.py
Labels: enhancement

#202 releasing `v3.0.0`
  cachier/version.info
Labels: release
