Repository python-cachier/cachier, pull requests merged in 2024-10, with the labels that each got.

#238 fix(lint): emergency bump for `docformatter`
  .pre-commit-config.yaml
Labels: bug, CI

#237 convert `_default_params` to dataclass
  .pre-commit-config.yaml
  src/cachier/__init__.py
  src/cachier/config.py
  src/cachier/core.py
  tests/test_core_lookup.py
  tests/test_defaults.py
  tests/test_general.py
  tests/test_pickle_core.py
Labels: enhancement

#239 convert `dict` entry to dataclass & typing
  .github/workflows/ci-test.yml
  pyproject.toml
  src/cachier/config.py
  src/cachier/core.py
  src/cachier/cores/base.py
  src/cachier/cores/memory.py
  src/cachier/cores/mongo.py
  src/cachier/cores/pickle.py
  tests/test_mongo_core.py
Labels: enhancement

#233 skip cashing for exceptions
  src/cachier/config.py
  src/cachier/core.py
  src/cachier/cores/memory.py
  src/cachier/cores/mongo.py
  src/cachier/cores/pickle.py
  tests/test_general.py
  tests/test_mongo_core.py
Labels: bug

#240 Release version 3.1.0
  src/cachier/version.info
Labels: release

#243 Release version 3.1.1
  src/cachier/version.info
Labels: release

#244 Fix typo in README.rst
  README.rst
Labels: documentation

#245 Update maintainers list in README.rst
  README.rst
Labels: documentation

#248 fix: crash with `None` & confusing tests
  pyproject.toml
  src/cachier/cores/pickle.py
  tests/test_pickle_core.py
Labels: bug

#249 fix reusing legacy pickle caches
  src/cachier/cores/pickle.py
Labels: bug

#250 typing: adding check and fixing
  .pre-commit-config.yaml
  src/cachier/config.py
  src/cachier/core.py
  src/cachier/cores/base.py
  src/cachier/cores/memory.py
  src/cachier/cores/mongo.py
  src/cachier/cores/pickle.py
  tests/test_general.py
Labels: enhancement, CI

#251 Release version 3.1.2
  src/cachier/version.info
Labels: release
